In [8]:
import os

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_csv = os.path.join(base_url, 'anime.csv')

print(anime_csv)

https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/anime.csv


In [9]:
import numpy as np
import pandas as pd

anime_csv = os.path.join(base_url, 'anime.csv')
pd.read_csv(anime_csv).head()

anime_id                              name  ... rating members
0     32281                    Kimi no Na wa.  ...   9.37  200630
1      5114  Fullmetal Alchemist: Brotherhood  ...   9.26  793665
2     28977                          Gintama°  ...   9.25  114262
3      9253                       Steins;Gate  ...   9.17  673572
4      9969                     Gintama&#039;  ...   9.16  151266

[5 rows x 7 columns]

In [1]:
list_arr = list(range(5))
print(list_arr)
print(type(list_arr))

[0, 1, 2, 3, 4]
<class 'list'>


In [3]:
import numpy as np
np_arr = np.array(range(5))
print(np_arr)
print(type(np_arr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr = np.array([0, 1, 2, 3, 4], dtype=float)
print(arr)
print(arr.dtype)
print(arr.astype(int))

[0. 1. 2. 3. 4.]
float64
[0 1 2 3 4]


In [7]:
list = [0, 1, 2, 3]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

list = [[0, 1, 2], [3, 4, 5]]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

1
(4,)
2
(2, 3)


In [13]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print("arr.shape : {}".format(arr.shape))
print("배열 요소의 수 : {}".format(arr.size))
print("배열의 길이 : {}".format(len(arr)))

arr.shape = 3,2
print("arr.shape : {}".format(arr.shape))
print("배열 요소의 수 : {}".format(arr.size))
print("배열의 길이 : {}".format(len(arr)))

arr.shape : (2, 3)
배열 요소의 수 : 6
배열의 길이 : 2
arr.shape : (3, 2)
배열 요소의 수 : 6
배열의 길이 : 3


In [15]:
x = np.arange(7)
print(x)
print(x[3])
x[0] = 10
print(x)

[0 1 2 3 4 5 6]
3
[10  1  2  3  4  5  6]


In [21]:
x = np.arange(1, 13, 1)
x.shape = 3,4
print(x)
print(x[2, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
배열의 길이 : 6


In [33]:
x = np.arange(7)
print(x)

print(x[1:4])
print(x[1:])
print(x[:4])
print(x[::2])

x = np.arange(1, 13, 1)
x.shape = 3, 4
print(x)
print(x[1:2, :2:3])
print(x[1:, :2])

x = np.arange(7)
print(x)
print(x < 3)
print(x > 7)
print(x[x < 3])
print(x[x % 2 == 0])

print(x[[1, 3, 5]])
x = np.arange(1, 13, 1).reshape(3, 4)
print(x)
print(x[[0, 2]])
print(x[1:2, 2])
print(x[[0,2], 2])
print(x[[0,2], :2])

[0 1 2 3 4 5 6]
[1 2 3]
[1 2 3 4 5 6]
[0 1 2 3]
[0 2 4 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]]
[[ 5  6]
 [ 9 10]]
[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]
[0 1 2]
[0 2 4 6]
[1 3 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


In [42]:
import pandas as pd

data = pd.Series([1, 2, 3, 4])
print(data)
print(type(data))
print(data.values)
print(type(data.values))
data = pd.Series([1, 2, 3, 4], dtype = "float")
print(data.dtype)
data = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
data['c'] = 5
print(data)

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4]
<class 'numpy.ndarray'>
float64
a    1
b    2
c    5
d    4
dtype: int64
{'china': 141500, 'japan': 12718, 'korea': 5180, 'usa': 32676}
china    141500
japan     12718
korea      5180
usa       32676
dtype: int64


In [47]:
population_dict = {
    'china': 141500,
    'japan': 12718,
    'korea': 5180,
    'usa': 32676
}
print(population_dict)
population = pd.Series(population_dict)
print(population)

gdp_dict = {
    'china': 1409250000,
    'japan': 516700000,
    'korea': 169320000,
    'usa': 2041280000,
}
gdp = pd.Series(gdp_dict)
print(gdp)

country = pd.DataFrame({
    'gdp': gdp,
    'populaion': population
})
print(country)



china    1409250000
japan     516700000
korea     169320000
usa      2041280000
dtype: int64
              gdp  populaion
china  1409250000     141500
japan   516700000      12718
korea   169320000       5180
usa    2041280000      32676


In [56]:
data = {
    'country': ['china', 'japan', 'korea', 'usa'],
    'gdp': [1409250000, 516700000, 169320000, 2041280000],
    'population': [141500, 12718, 5180, 32676]
}
country = pd.DataFrame(data)
country = country.set_index('country')
print(country)
print(country.shape)
print(country.size)
print(country.ndim)
print(country.values)

country.index.name = "Country"
country.columns.name = "Info"
print(country.index)
print(country.columns)

country.to_csv("./country.csv")
country.to_excel("./country.xlsx")

country = pd.read_csv("./country.csv")
country = pd.read_excel("./country.xlsx")

                gdp  population
country                        
china    1409250000      141500
japan     516700000       12718
korea     169320000        5180
usa      2041280000       32676
(4, 2)
8
2
[[1409250000     141500]
 [ 516700000      12718]
 [ 169320000       5180]
 [2041280000      32676]]
Index(['china', 'japan', 'korea', 'usa'], dtype='object', name='Country')
Index(['gdp', 'population'], dtype='object', name='Info')


PermissionError: [Errno 13] Permission denied: './country.csv'